### PR TITLE
Allow empty serializedApiMethods and Authenticate User with api-guard middleware

### PR DESCRIPTION
**Pull request by petitkoalak**
I just was notified of the acceptation of @gholol pull request ( https://github.com/chrisbjr/api-guard/pull/85 ) about api-guard as a laravel middleware.
These are the changes I made from his code.

Basically it just let the possibility to send no "options" and it authenticate the current user so it becomes accessible via Auth::user()

The last thing I would might change on this, is : Adding the possibility to send "$serializedApiMethods" as plain php Array and not as serialized array, let me know if you interrested and I'll commit modifications

You did there great work, hope you'll accept this request

### CODE REVIEW

**Comment by petitkoalak** [comment]
Yes, apache dependency is bad, but we shouldnn't hard code the header key, so following code would be better :
`$api_key = $request->headers[Config::get('apiguard.keyName', 'X-Authorization')];`

**Comment by ddimaria** [comment]
You can refactor (for efficiency and PSR compliance) the existing code by just reusing the $key var earlier in this overly long method:

```
// login User
      $user_id = App::make(Config::get('apiguard.model', 'Chrisbjr\ApiGuard\Models\ApiKey'))->where('key', $key) ->pluck('user_id');

      if($user_id !== 0) {
        Auth::loginUsingId($user_id);
      }
      
      return $next($request);
```

**Comment by petitkoalak** [comment]
Feel free to change any part of this code and submit it, i just edited https://github.com/chrisbjr/api-guard/pull/85 for my needs

**Comment by ddimaria** [comment]
Cool, I added a PR to fix this: https://github.com/chrisbjr/api-guard/pull/91

**Comment by ddimaria** [comment]
Actually, we should remove all of that code..not sure why it's there...creates a dependency on a user, and doesn't work if using namespacing (\Auth).  I'll remove it all.  Author should write their own middleware to do this user auth.

**Comment by petitkoalak** [comment]
Refactoring it, ofc yes but removing it ? no, i don't think so.

**Comment by ddimaria** [comment]
Thanks!  I agree with you...looking back at the code.  A User model that implements Illuminate\Contracts\Auth\Authenticatable should be a requirement for this, and is configurable via config/auth.php.  This might be something to document to for clarity.

**Pull request merged**
