### PR TITLE
Compatibility with Laravel 5.5 + readme fix

### PR DESCRIPTION
**Pull request by junaidnasir**

### CODE REVIEW

**Comment by chrisbjr** [comment]
Hi @junaidnasir appreciate this pull request. Can you squash it into one commit though? Thanks a lot!

**Comment by junaidnasir** [comment]
sure will submit another pr

**Comment by chrisbjr** [comment]
also, you added your name to the license..

**Comment by junaidnasir** [comment]
Sorry for that, I wanted to use the updated package. and I thought you no longer maintain this so i submitted my own to packgist. will retract that now and submit pr

**Pull request closed without merging**
